package com.example.hrms.core.adapter.Mernis;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.5.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public interface TRDIServiceEvents
{
    void Starting();
    void Completed(TRDOperationResult result);
}
